server:
  port: 8001

spring:
  application:
    name: service-edu
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ol_edu?serverTimezone=GMT%2B8
    username: root
    password: rootroot
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 1800000
    password: slimbohredis
    lettuce:
      pool:
        max-active: 20
        max-idle: 5

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
feign:
  hystrix:
    enabled: true
  httpclient:
    connection-timeout: 8000


